[build]
  base = "."
  publish = "public"
  command = "npm run build"
  functions = "functions"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/politique-confidentialite"
  to = "/politique-confidentialite.html"
  status = 200

[[redirects]]
  from = "/conditions-utilisation"
  to = "/conditions-utilisation.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { language = ["fr"] }

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true 